AMQP_URI: amqp://admin:secretpassword@rabbitmq:5672/

REDIS_URI: redis://user:secretpassword@redis-master:6379/11

GRPC_BIND_PORT: 50051

LOGGING:
    version: 1
    disable_existing_loggers: False
    formatters:
        default:
            format: "%(asctime)-15s [%(levelname)-4s] [products] [%(name)-12s] %(message)s"
    handlers:
        default:
            level: INFO
            formatter: default
            class: logging.StreamHandler
    root:
        level: INFO
        propagate: True
        handlers: [default]
