# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

from . import orders_pb2 as orders__pb2


class ordersStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.get_order = channel.unary_unary(
        '/orders.orders/get_order',
        request_serializer=orders__pb2.GetOrderRequest.SerializeToString,
        response_deserializer=orders__pb2.OrderResponse.FromString,
        )
    self.create_order = channel.unary_unary(
        '/orders.orders/create_order',
        request_serializer=orders__pb2.CreateOrderRequest.SerializeToString,
        response_deserializer=orders__pb2.OrderResponse.FromString,
        )
    self.update_order = channel.unary_unary(
        '/orders.orders/update_order',
        request_serializer=orders__pb2.UpdateOrderRequest.SerializeToString,
        response_deserializer=orders__pb2.OrderResponse.FromString,
        )
    self.delete_order = channel.unary_unary(
        '/orders.orders/delete_order',
        request_serializer=orders__pb2.DeleteOrderRequest.SerializeToString,
        response_deserializer=orders__pb2.OrderDeletedResponse.FromString,
        )


class ordersServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def get_order(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def create_order(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def update_order(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def delete_order(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_ordersServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'get_order': grpc.unary_unary_rpc_method_handler(
          servicer.get_order,
          request_deserializer=orders__pb2.GetOrderRequest.FromString,
          response_serializer=orders__pb2.OrderResponse.SerializeToString,
      ),
      'create_order': grpc.unary_unary_rpc_method_handler(
          servicer.create_order,
          request_deserializer=orders__pb2.CreateOrderRequest.FromString,
          response_serializer=orders__pb2.OrderResponse.SerializeToString,
      ),
      'update_order': grpc.unary_unary_rpc_method_handler(
          servicer.update_order,
          request_deserializer=orders__pb2.UpdateOrderRequest.FromString,
          response_serializer=orders__pb2.OrderResponse.SerializeToString,
      ),
      'delete_order': grpc.unary_unary_rpc_method_handler(
          servicer.delete_order,
          request_deserializer=orders__pb2.DeleteOrderRequest.FromString,
          response_serializer=orders__pb2.OrderDeletedResponse.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'orders.orders', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
